services:
  db:
    image: postgres:16
    container_name: fastmarket-postgres
    environment:
      POSTGRES_DB: fastmarket
      POSTGRES_USER: fastmarket
      POSTGRES_PASSWORD: fastmarket
    ports:
      - "5432:5432"
    volumes:
      - fastmarket_pgdata:/var/lib/postgresql/data

volumes:
  fastmarket_pgdata:
